services:
  # --- INFRASTRUCTURE ---
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flashsale
    ports:
      - "5433:5432" # Mapped to 5433 on host to avoid local conflicts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d flashsale"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      # KRaft mode configuration
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  # --- APPLICATIONS ---
  order-service:
    build:
      context: .
      dockerfile: Dockerfile.base
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9092
      - DATABASE_URL=postgresql://user:password@db:5432/flashsale
    command: npm start -w apps/order-service
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started

  order-consumer:
    build:
      context: .
      dockerfile: Dockerfile.base
    environment:
      - REDIS_HOST=redis
      - KAFKA_BROKERS=kafka:9092
      - DATABASE_URL=postgresql://user:password@db:5432/flashsale
    command: npm start -w apps/order-consumer
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started

  expiry-server:
    build:
      context: .
      dockerfile: Dockerfile.base
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://user:password@db:5432/flashsale
    command: npm start -w apps/expiry-server
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
